# Generated by Django 4.2.17 on 2025-02-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=16)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=16)),
                ('color', models.CharField(max_length=16)),
                ('size', models.CharField(max_length=16)),
                ('stock', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('storage_location', models.CharField(max_length=16)),
                ('operation', models.CharField(max_length=16)),
                ('operator', models.CharField(max_length=16)),
                ('remark', models.CharField(max_length=16)),
            ],
        ),
    ]
