# Generated by Django 4.2.17 on 2025-02-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='storage_location',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=16)),
                ('location_address', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory_record',
            name='color',
        ),
        migrations.RemoveField(
            model_name='inventory_record',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventory_record',
            name='size',
        ),
        migrations.RemoveField(
            model_name='inventory_record',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='inventory_record',
            name='storage_location',
        ),
        migrations.AddField(
            model_name='inventory',
            name='color',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='size',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='storage_location_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
