# Generated by Django 4.2.17 on 2025-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_storage_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory_record',
            old_name='date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='inventory_record',
            old_name='operation',
            new_name='operation_type',
        ),
        migrations.RemoveField(
            model_name='inventory_record',
            name='remark',
        ),
        migrations.AddField(
            model_name='inventory_record',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory_record',
            name='storage_location_id',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
