# Generated by Django 4.2.17 on 2025-02-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
                ('customer_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=24)),
                ('sku_code', models.CharField(max_length=24)),
                ('sku_num', models.IntegerField()),
                ('sku_price', models.CharField(max_length=10)),
            ],
        ),
    ]
