# Generated by Django 5.1.5 on 2025-02-26 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='sku_code',
            new_name='sku_id',
        ),
    ]
