# Generated by Django 4.2.17 on 2025-02-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sku',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('spu_id', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('price', models.FloatField()),
                ('create_date', models.DateTimeField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='spu',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField(null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('pattern_design', models.CharField(max_length=20)),
                ('design_source', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=20)),
            ],
        ),
    ]
