# Generated by Django 5.1.5 on 2025-02-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spu',
            name='img',
            field=models.ImageField(default=1, upload_to='style/spu'),
            preserve_default=False,
        ),
    ]
