# Generated by Django 5.1.5 on 2025-02-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0002_spu_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spu',
            name='design_source',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spu',
            name='img',
            field=models.ImageField(null=True, upload_to='style/spu'),
        ),
        migrations.AlterField(
            model_name='spu',
            name='pattern_design',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spu',
            name='remark',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spu',
            name='season',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
