# Generated by Django 4.2.17 on 2025-02-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0003_alter_spu_design_source_alter_spu_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
