# Generated by Django 4.2.17 on 2025-02-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0004_alter_sku_cost_alter_sku_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='price',
        ),
        migrations.AddField(
            model_name='spu',
            name='cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='spu',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
