# Generated by Django 4.2.17 on 2025-02-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0005_remove_sku_cost_remove_sku_price_spu_cost_spu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='barcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
