# Generated by Django 4.2.17 on 2025-03-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0006_sku_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spu',
            options={'permissions': [('can_view_spu', 'Can view spu')]},
        ),
    ]
