# Generated by Django 4.2.17 on 2025-03-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0008_alter_spu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spu',
            options={},
        ),
    ]
